services:
  
  order-service:
    build:
      context: orders/order-service
      dockerfile: Dockerfile
    container_name: order-service
    labels:
      structurizr.name: "Order Application"
      structurizr.description: "Subscribes to certain Commands, protects the DomainLogic, emits DomainEvents to the broker"
      structurizr.technology: "Node.js, Express"
      structurizr.port: "${ORDER_PORT}"
      structurizr.group: "Order Domain"
      structurizr.depends_on.broker-service: "subscribe to certain Commands, publish DomainEvents"
      structurizr.depends_on.order-eventstore-service: "fetch streams, commit DomainEvents"
    depends_on:
      - broker-service
      - order-eventstore-service
    ports:
      - "${ORDER_PORT}:4000"
    environment:
      - BROKER_URL=amqp://guest:guest@broker-service:5672
      - EVENTSTORE_URL=http://order-eventstore-service:${ORDER_EVENTSTORE_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-eventstore-service:
    build:
      context: orders/order-eventstore-service
      dockerfile: Dockerfile
    container_name: order-eventstore-service
    labels:
      structurizr.name: "Order EventStore"
      structurizr.description: "Durable, append-only event journal"
      structurizr.technology: "Node.js, Express"
      structurizr.port: "${ORDER_EVENTSTORE_PORT}"
      structurizr.group: "Order Domain::Event Store"
      structurizr.depends_on.order-eventstore-db: "read, write"
    depends_on:
      - order-eventstore-db
    environment:
      - MONGO_URL=mongodb://order-eventstore-db:27017
    ports:
      - "${ORDER_EVENTSTORE_PORT}:4001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  order-eventstore-db:
    image: mongo:7
    container_name: order-eventstore-db
    command: ["--config", "/etc/mongo/mongo.conf"]
    volumes:
      - order_eventstore_data:/data/db
      - order_eventstore_config:/data/configdb
      - ./mongo.conf:/etc/mongo/mongo.conf:ro
    labels:
      structurizr.name: "Order EventStore Database"
      structurizr.description: "Append only journal for DomainEvents"
      structurizr.technology: "MongoDB"
      structurizr.port: "default"
      structurizr.group: "Order Domain::Event Store"
      structurizr.type: "database"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  order_eventstore_data:
  order_eventstore_config: