x-otel-env: &otel_env
  NODE_OPTIONS: "--require @daveloper/otel"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4318/v1/metrics
  OTEL_RESOURCE_ATTRIBUTES: service.version=${SERVICE_VERSION:-0.1.0},deployment.environment=${DEPLOY_ENV:-dev}

services:
  otel-collector:
    profiles: ["obs"]
    image: otel/opentelemetry-collector:0.104.0
    container_name: otel-collector
    command: ["--config=/etc/otel/otel-collector.yaml"]
    volumes:
      - ./shared/opentelemetry/otel-collector.yaml:/etc/otel/otel-collector.yaml:ro
    depends_on:
      - tempo
    ports:
      - "${OTEL_GRPC_PORT}:4317" # OTLP gRPC
      - "${OTEL_HTTP_PORT}:4318" # OTLP HTTP
      - "9464:9464" # Prometheus scrape van collector-metrics
    labels:
      structurizr.name: "OpenTelemetry Collector"
      structurizr.description: "Recieve OTLP (traces/metrics) and export to Tempo/Prometheus"
      structurizr.technology: "OpenTelemetry Collector"
      structurizr.port: "${OTEL_GRPC_PORT},${OTEL_HTTP_PORT},9464"
      structurizr.group: "Observability"
      structurizr.type: "telemetry"
      structurizr.depends_on.tempo: "export traces"

  prometheus:
    profiles: ["obs"]
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    depends_on:
      - otel-collector
      - broker-service
    labels:
      structurizr.name: "Prometheus"
      structurizr.description: "Scrape metrics van OTel Collector en RabbitMQ Exporter"
      structurizr.technology: "Prometheus"
      structurizr.port: "${PROMETHEUS_PORT}"
      structurizr.group: "Observability"
      structurizr.type: "telemetry"
      structurizr.depends_on.otel-collector: "get metrics"
      structurizr.depends_on.broker-service: "scrape metrics and traces"

  tempo:
    profiles: ["obs"]
    image: grafana/tempo:2.6.1
    container_name: tempo
    command: ["-config.file=/etc/tempo/config.yaml"]
    volumes:
      - ./observability/tempo.yaml:/etc/tempo/config.yaml:ro
      - tempo_data:/var/tempo
    ports:
      - "${TEMPO_HTTP_PORT}:3200"  # UI/Query
    labels:
      structurizr.name: "Tempo"
      structurizr.description: "Opslag voor traces (OpenTelemetry)"
      structurizr.technology: "Grafana Tempo"
      structurizr.port: "${TEMPO_HTTP_PORT}"
      structurizr.group: "Observability"
      structurizr.type: "telemetry"

  grafana:
    profiles: ["obs"]
    image: grafana/grafana:11.1.0
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus
      - tempo
    labels:
      structurizr.name: "Grafana"
      structurizr.description: "Dashboards en trace/metrics Explore"
      structurizr.technology: "Grafana"
      structurizr.port: "${GRAFANA_PORT}"
      structurizr.group: "Observability"
      structurizr.type: "telemetry"
      structurizr.depends_on.prometheus: "get metrics"
      structurizr.depends_on.tempo: "explore traces"
  
  shop-bff-service:
    profiles: ["obs"]
    environment:
      <<: *otel_env
      OTEL_SERVICE_NAME: shop-bff-service

  order-service:
    profiles: ["obs"]
    environment:
      <<: *otel_env
      OTEL_SERVICE_NAME: order-service

  order-eventstore-service:
    profiles: ["obs"]
    environment:
      <<: *otel_env
      OTEL_SERVICE_NAME: order-eventstore-service

  shop-projection-service:
    profiles: ["obs"]
    environment:
      <<: *otel_env
      OTEL_SERVICE_NAME: shop-projection-service

volumes:
  prometheus_data:
  tempo_data:
  grafana_data:
