services:

  broker-service:
    image: rabbitmq:3-management
    container_name: broker-service
    labels:
      structurizr.name: "Broker"
      structurizr.description: "Provides a robust messaging broker with management UI"
      structurizr.technology: "RabbitMQ"
      structurizr.port: "${RABBITMQ_UI_PORT}"
      structurizr.group: "Event Platform"
      structurizr.type: "broker"
    expose:
      - "5672" # amqp
    ports:
      - "${RABBITMQ_UI_PORT}:15672" # expose for UI access via localhost
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - broker_rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  broker_rabbitmq_data:
