services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    labels:
      com.diagram.name: "Broker"
      com.diagram.technology: "RabbitMQ"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    depends_on:
      - rabbitmq
    labels:
      com.diagram.name: "Order ApplicationService"
      com.diagram.technology: "Node.js, Eventbus"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-projection-service:
    build:
      context: .
      dockerfile: order-projection-service/Dockerfile
    depends_on:
      - rabbitmq
      - shop-bff-service
    labels:
      com.diagram.name: "Order ProjectionService"
      com.diagram.technology: "Node.js, Eventbus, Socket.io-client"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  shop-bff-service:
    build:
      context: .
      dockerfile: shop-bff-service/Dockerfile
    depends_on:
      - rabbitmq
    labels:
      com.diagram.name: "Shop BFF"
      com.diagram.technology: "Node.js, Socket.io"
    ports:
      - "4000:4000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  shop-frontend:
    build:
      context: ./shop-frontend
      dockerfile: Dockerfile
    depends_on:
      - shop-bff-service
    labels:
      com.diagram.name: "Shop Frontend"
      com.diagram.technology: "NGINX, html/js, Socket.io.min.js"
    ports:
      - "3000:3000"
