FROM node:22-alpine AS base

# handy tools
RUN apk add --no-cache bash curl \
 && curl -fsSL https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -o /usr/local/bin/wait-for-it \
 && chmod +x /usr/local/bin/wait-for-it

WORKDIR /usr/src/app

# Copy the workspace manifest + all necessary folders
COPY package*.json tsconfig.base.json ./
COPY shared/ ./shared
COPY observability/opentelemetry/ ./observability/opentelemetry

RUN npm install

RUN npm run build
