services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    labels:
      structurizr.name: "Broker"
      structurizr.description: "Provides a robust messaging broker with management UI"
      structurizr.technology: "RabbitMQ"
      structurizr.group: "Event Platform"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf.d:/etc/rabbitmq/conf.d/20-logging.conf:ro
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

  event-store:
    build:
      context: .
      dockerfile: event-store/Dockerfile
    container_name: event-store
    labels:
      structurizr.name: "EventStore"
      structurizr.description: "Durable, append-only event journal"
      structurizr.technology: "Node.js, Express"
      structurizr.group: "Order Domain"
      structurizr.type: "database"
      structurizr.depends_on.rabbitmq: "subscribe to all DomainEvents"
    depends_on:
      - rabbitmq
    ports:
      - "7000:7000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    labels:
      structurizr.name: "OrderApplicationService"
      structurizr.description: "Subscribes to certain Commands, protects the DomainLogic, emits DomainEvents to the broker"
      structurizr.technology: "Node.js, Broker"
      structurizr.group: "Order Domain"
      structurizr.depends_on.rabbitmq: "subscribe to certain Commands, publish DomainEvents"
      structurizr.depends_on.event-store: "fetch streams"
    depends_on:
      - rabbitmq
      - event-store
    ports:
      - "6000:6000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  shop-projection-service:
    build:
      context: .
      dockerfile: shop-projection-service/Dockerfile
    container_name: shop-projection-service
    labels:
      structurizr.name: "ShopProjectionService"
      structurizr.description: "Handles fetches, subscribes to DomainEvents, denormalizes and upserts Payloads, pushes Payloads to bff"
      structurizr.technology: "Node.js, Broker, Socket.io-client"
      structurizr.group: "Shop::Projection"
      structurizr.depends_on.rabbitmq: "subscribe to certain DomainEvents"
      structurizr.depends_on.shop-bff-service: "listen for Queries and push Payloads"
      structurizr.depends_on.shop-projection-db: "fetch data, upsert data"
      structurizr.depends_on.event-store: "fetch streams"
    depends_on:
      - rabbitmq
      - event-store
      - shop-bff-service
      - shop-projection-db
    ports:
      - "5000:5000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - MONGO_URL=mongodb://shop-projection-db:27017
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  shop-projection-db:
    image: mongo:7
    container_name: shop-projection-db
    command: ["--config", "/etc/mongo/mongo.conf"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo.conf:/etc/mongo/mongo.conf:ro
    labels:
      structurizr.name: "ShopProjectionDB"
      structurizr.description: "Read DB for denormalized views"
      structurizr.technology: "MongoDB"
      structurizr.group: "Shop::Projection"
      structurizr.type: "database"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  shop-bff-service:
    build:
      context: .
      dockerfile: shop-bff-service/Dockerfile
    container_name: shop-bff-service
    labels:
      structurizr.name: "Shop BFF"
      structurizr.description: "Exposes and guards WebSocket/APIs, publishes Commands to the broker, forwards Queries to projections, listens for Payloads from projections and forwards them to web clients"
      structurizr.technology: "Node.js, Broker, Socket.io"
      structurizr.group: "Shop"
      structurizr.depends_on.rabbitmq: "publish Commands"
    depends_on:
      - rabbitmq
    ports:
      - "4000:4000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  shop-frontend:
    build:
      context: ./shop-frontend
      dockerfile: Dockerfile
    container_name: shop-frontend
    labels:
      structurizr.name: "Shop Frontend"
      structurizr.description: "Serves static files"
      structurizr.technology: "Nginx"
      structurizr.group: "Shop::Website"
      structurizr.type: "webserver"
      structurizr.depends_on.shop-bff-service: "send Commands, send fetches, listen for Payloads"
    depends_on:
      - shop-bff-service
    ports:
      - "3000:3000"

volumes:
  mongo_data: