services:
  otel-collector:
    profiles: ["obs"]
    image: otel/opentelemetry-collector:0.104.0
    container_name: otel-collector
    command: ["--config=/etc/otel/otel-collector.yaml"]
    volumes:
      - ./observability/otel-collector.yaml:/etc/otel/otel-collector.yaml:ro
    ports:
      - "${OTEL_GRPC_PORT}:4317"   # OTLP gRPC
      - "${OTEL_HTTP_PORT}:4318"   # OTLP HTTP
    labels:
      structurizr.name: "OpenTelemetry Collector"
      structurizr.description: "Recieve OTLP (traces/metrics) and export to Tempo/Prometheus"
      structurizr.technology: "OpenTelemetry Collector"
      structurizr.port: "${OTEL_GRPC_PORT},${OTEL_HTTP_PORT}"
      structurizr.group: "Observability"

  prometheus:
    profiles: ["obs"]
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    labels:
      structurizr.name: "Prometheus"
      structurizr.description: "Scrapet metrics van OTel Collector en RabbitMQ Exporter"
      structurizr.technology: "Prometheus"
      structurizr.port: "${PROMETHEUS_PORT}"
      structurizr.group: "Observability"

  tempo:
    profiles: ["obs"]
    image: grafana/tempo:2.6.1
    container_name: tempo
    command: ["-config.file=/etc/tempo/config.yaml"]
    volumes:
      - ./observability/tempo.yaml:/etc/tempo/config.yaml:ro
      - tempo_data:/var/tempo
    ports:
      - "${TEMPO_HTTP_PORT}:3200"  # UI/Query
    labels:
      structurizr.name: "Tempo"
      structurizr.description: "Opslag voor traces (OpenTelemetry)"
      structurizr.technology: "Grafana Tempo"
      structurizr.port: "${TEMPO_HTTP_PORT}"
      structurizr.group: "Observability"

  grafana:
    profiles: ["obs"]
    image: grafana/grafana:11.1.0
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    ports:
      - "${GRAFANA_PORT}:3000"
    labels:
      structurizr.name: "Grafana"
      structurizr.description: "Dashboards en trace/metrics Explore"
      structurizr.technology: "Grafana"
      structurizr.port: "${GRAFANA_PORT}"
      structurizr.group: "Observability"
  
  # ---- App-services: OTel env alleen als profiel 'obs' aan staat ----

  shop-bff-service:
    profiles: ["obs"]
    environment:
      OTEL_SERVICE_NAME: shop-bff-service
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4318/v1/metrics
      OTEL_RESOURCE_ATTRIBUTES: service.version=${SERVICE_VERSION:-0.1.0},deployment.environment=${DEPLOY_ENV:-dev}

  order-service:
    profiles: ["obs"]
    environment:
      OTEL_SERVICE_NAME: order-service
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4318/v1/metrics
      OTEL_RESOURCE_ATTRIBUTES: service.version=${SERVICE_VERSION:-0.1.0},deployment.environment=${DEPLOY_ENV:-dev}

  order-eventstore-service:
    profiles: ["obs"]
    environment:
      OTEL_SERVICE_NAME: order-eventstore-service
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4318/v1/metrics
      OTEL_RESOURCE_ATTRIBUTES: service.version=${SERVICE_VERSION:-0.1.0},deployment.environment=${DEPLOY_ENV:-dev}

  shop-projection-service:
    profiles: ["obs"]
    environment:
      OTEL_SERVICE_NAME: shop-projection-service
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4318/v1/metrics
      OTEL_RESOURCE_ATTRIBUTES: service.version=${SERVICE_VERSION:-0.1.0},deployment.environment=${DEPLOY_ENV:-dev}

volumes:
  prometheus_data:
  tempo_data:
  grafana_data:
