apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://otel-prometheus:9090 
    isDefault: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://otel-tempo:3200
