openapi: 3.1.0
info:
  title: BFF Service API
  version: 1.0.0
paths:
  /commands:
    post:
      summary: Send a command to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                payload:
                  type: object
      responses:
        '202':
          description: Accepted
  /events:
    get:
      summary: Server-Sent Events for domain events
      responses:
        '200':
          description: SSE stream
          content:
            text/event-stream:
              schema:
                type: string